/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package littlemangame.tutorial;

import littlemangame.genericGui.GenericOfficeView;
import littlemangame.genericLittleMan.GenericLittleManCommander;

/**
 *
 * @author brian
 */
public class TutorialOfficeView extends javax.swing.JPanel implements GenericOfficeView<TutorialInputPanel, TutorialOutputPanel> {

    /**
     * Creates new form TutorialOfficeView
     */
    public TutorialOfficeView() {
        initComponents();
    }

    @Override
    public TutorialInputPanel getInputPanel() {
        return tutorialInputPanel;
    }

    @Override
    public TutorialOutputPanel getOutputPanel() {
        return tutorialOutputPanel;
    }

    @Override
    public void registerLittleManCommander(GenericLittleManCommander<?> littleManCommander) {
        gameCanvas1.getRenderer().addDrawable(littleManCommander);
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gameCanvas1 = new GameGui.GameCanvas();
        tutorialOutputPanel = new littlemangame.tutorial.TutorialOutputPanel();
        tutorialInputPanel = new littlemangame.tutorial.TutorialInputPanel();

        javax.swing.GroupLayout gameCanvas1Layout = new javax.swing.GroupLayout(gameCanvas1);
        gameCanvas1.setLayout(gameCanvas1Layout);
        gameCanvas1Layout.setHorizontalGroup(
            gameCanvas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameCanvas1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(gameCanvas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tutorialInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tutorialOutputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(485, Short.MAX_VALUE))
        );
        gameCanvas1Layout.setVerticalGroup(
            gameCanvas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameCanvas1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(tutorialOutputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tutorialInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(171, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(gameCanvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(gameCanvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GameGui.GameCanvas gameCanvas1;
    private littlemangame.tutorial.TutorialInputPanel tutorialInputPanel;
    private littlemangame.tutorial.TutorialOutputPanel tutorialOutputPanel;
    // End of variables declaration//GEN-END:variables
}
