/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package littlemangame.tutorial.gui;

import java.awt.event.ActionListener;
import littlemangame.notebookdeveloper.submissioncontrols.SubmissionControlGui;

/**
 *
 * @author brian
 */
public class SubmissionControllerTutorialGui extends SubmissionControlGui {

    private final TutorialDialogue tutorialDialogue;

    /**
     * Creates new form SubmissionControllerTutorialGui
     */
    public SubmissionControllerTutorialGui() {
        super();
        tutorialDialogue = new TutorialDialogue();
        replaceDummyPanel(tutorialDialogue);
    }

    @Override
    protected void hidePanels() {
        super.hidePanels();
        tutorialDialogue.setVisible(false);
    }

    public void showDialoguePanel() {
        hidePanels();
        tutorialDialogue.setVisible(true);
    }

    public void printDialogue(String message) {
        tutorialDialogue.setText(message);
    }

    public void addActionListener(ActionListener l) {
        tutorialDialogue.addActionListener(l);
    }

    public void removeActionListener(ActionListener l) {
        tutorialDialogue.removeActionListener(l);
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
