/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package littlemangame.notebookdeveloper.submissioncontrols;

import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.GroupLayout;
import javax.swing.JLayeredPane;
import littlemangame.notebookdeveloper.GenericNotebookDeveloper;
import littlemangame.notebookdeveloper.speedcontroller.SpeedController;

/**
 *
 * @author brian
 * @param <T>
 */
public class SubmissionControlGui<T extends GenericNotebookDeveloper<?>>
        extends javax.swing.JPanel {

    private T notebookDeveloper;

    /**
     * Creates new form SubmissionControlGui
     *
     */
    public SubmissionControlGui() {
        initComponents();
        baseLayeredPane.setLayer(speedPanel, JLayeredPane.DEFAULT_LAYER, 0);
        baseLayeredPane.setLayer(submissionPanel, JLayeredPane.DEFAULT_LAYER, 1);
        speedPanel.setVisible(false);
        submissionPanel.setVisible(true);
        testButton.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                showSpeedPanel();
                speedControllerGui.resume();
            }

        });
        submitButton.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                final String resultString = SubmissionControlGui.this.notebookDeveloper.submitNotebookSolutionAttempt();
                printResultMessage(resultString);
            }

        });
        speedControllerGui.setEndTestAction(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                showSubmissionPanel();
                SubmissionControlGui.this.notebookDeveloper.endTest();
            }

        });
    }

    public void setEditMemoryAction(ActionListener l) {
        final ActionListener[] originalActionListeners = editMemoryButton.getActionListeners();
        for (ActionListener actionListener : originalActionListeners) {
            editMemoryButton.removeActionListener(actionListener);
        }
        editMemoryButton.addActionListener(l);
        for (ActionListener actionListener : originalActionListeners) {
            editMemoryButton.addActionListener(actionListener);
        }
    }

    public void removeEditMemoryAction(ActionListener actionListener) {
        editMemoryButton.removeActionListener(actionListener);
    }

    protected void printResultMessage(String message) {
        consoleTextArea.append(message);
        consoleTextArea.setCaretPosition(0);
    }

    public final void showSpeedPanel() {
        hidePanels();
        speedPanel.setVisible(true);
    }

    public void registerSpeedController(SpeedController speedController) {
        speedControllerGui.registerSpeedController(speedController);
    }

    public void registerNotebookDeveloper(T notebookDeveloper) {
        this.notebookDeveloper = notebookDeveloper;
    }

    public final void showSubmissionPanel() {
        hidePanels();
        submissionPanel.setVisible(true);
    }

    protected void hidePanels() {
        speedPanel.setVisible(false);
        submissionPanel.setVisible(false);
    }

//    public SpeedControllerGui getSpeedControllerGui() {
//        return speedControllerGui;
//    }
    final protected JLayeredPane getBaseLayeredPane() {
        return baseLayeredPane;
    }

    final protected void replaceDummyPanel(Component newComponent) {
        final GroupLayout groupLayout = (GroupLayout) baseLayeredPane.getLayout();

        try {
            groupLayout.replace(dummyPanel, newComponent);
        } catch (IllegalArgumentException e) {
            throw new IllegalStateException("dummy panel has already been replaced.");
        }

    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        baseLayeredPane = new javax.swing.JLayeredPane();
        submissionPanel = new javax.swing.JPanel();
        consoleTextScrollPane = new javax.swing.JScrollPane();
        consoleTextArea = new javax.swing.JTextArea();
        dummyPanel = new javax.swing.JPanel();
        speedPanel = new javax.swing.JPanel();
        speedControllerGui = new littlemangame.notebookdeveloper.speedcontroller.SpeedControllerGui();

        submitButton.setText("Submit");

        editMemoryButton.setText("Edit Notebook");

        testButton.setText("Test");

        consoleTextArea.setEditable(false);
        consoleTextArea.setColumns(20);
        consoleTextArea.setLineWrap(true);
        consoleTextArea.setRows(3);
        consoleTextArea.setWrapStyleWord(true);
        consoleTextScrollPane.setViewportView(consoleTextArea);

        javax.swing.GroupLayout submissionPanelLayout = new javax.swing.GroupLayout(submissionPanel);
        submissionPanel.setLayout(submissionPanelLayout);
        submissionPanelLayout.setHorizontalGroup(
            submissionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(submissionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(submissionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(submissionPanelLayout.createSequentialGroup()
                        .addComponent(editMemoryButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(testButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(consoleTextScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        submissionPanelLayout.setVerticalGroup(
            submissionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(submissionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(submissionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(consoleTextScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(submissionPanelLayout.createSequentialGroup()
                        .addComponent(testButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(submissionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editMemoryButton)
                            .addComponent(submitButton))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dummyPanelLayout = new javax.swing.GroupLayout(dummyPanel);
        dummyPanel.setLayout(dummyPanelLayout);
        dummyPanelLayout.setHorizontalGroup(
            dummyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 521, Short.MAX_VALUE)
        );
        dummyPanelLayout.setVerticalGroup(
            dummyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout speedPanelLayout = new javax.swing.GroupLayout(speedPanel);
        speedPanel.setLayout(speedPanelLayout);
        speedPanelLayout.setHorizontalGroup(
            speedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(speedPanelLayout.createSequentialGroup()
                .addComponent(speedControllerGui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );
        speedPanelLayout.setVerticalGroup(
            speedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(speedPanelLayout.createSequentialGroup()
                .addComponent(speedControllerGui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout baseLayeredPaneLayout = new javax.swing.GroupLayout(baseLayeredPane);
        baseLayeredPane.setLayout(baseLayeredPaneLayout);
        baseLayeredPaneLayout.setHorizontalGroup(
            baseLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baseLayeredPaneLayout.createSequentialGroup()
                .addComponent(speedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(submissionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dummyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        baseLayeredPaneLayout.setVerticalGroup(
            baseLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baseLayeredPaneLayout.createSequentialGroup()
                .addGroup(baseLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(speedPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(submissionPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(baseLayeredPaneLayout.createSequentialGroup()
                .addComponent(dummyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        baseLayeredPane.setLayer(submissionPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        baseLayeredPane.setLayer(dummyPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        baseLayeredPane.setLayer(speedPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        speedPanel.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(baseLayeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(baseLayeredPane)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane baseLayeredPane;
    protected javax.swing.JTextArea consoleTextArea;
    private javax.swing.JScrollPane consoleTextScrollPane;
    private javax.swing.JPanel dummyPanel;
    protected final javax.swing.JButton editMemoryButton = new javax.swing.JButton();
    private littlemangame.notebookdeveloper.speedcontroller.SpeedControllerGui speedControllerGui;
    private javax.swing.JPanel speedPanel;
    private javax.swing.JPanel submissionPanel;
    protected final javax.swing.JButton submitButton = new javax.swing.JButton();
    protected final javax.swing.JButton testButton = new javax.swing.JButton();
    // End of variables declaration//GEN-END:variables
}
