/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package littlemangame;

import GameGui.BaseGameGui;
import java.awt.GridLayout;
import littlemangame.genericGui.GenericNotebookDeveloperGui;

/**
 *
 * @author brian
 * @param <T>
 */
public class GenericLittleManGui<T extends GenericNotebookDeveloperGui<?, ?>>
        extends BaseGameGui {

    private final T genericNotebookDeveloperGui;

    /**
     * Creates new form LittleManGui
     *
     * @param notebookDeveloperGui
     */
    public GenericLittleManGui(T notebookDeveloperGui) {
        super();
        initComponents();
        notebookDeveloperHolder.setLayout(new GridLayout());
        notebookDeveloperHolder.add(notebookDeveloperGui);
        this.genericNotebookDeveloperGui = notebookDeveloperGui;
    }

    public T getNotebookDeveloperGui() {
        return genericNotebookDeveloperGui;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        notebookDeveloperHolder = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout notebookDeveloperHolderLayout = new javax.swing.GroupLayout(notebookDeveloperHolder);
        notebookDeveloperHolder.setLayout(notebookDeveloperHolderLayout);
        notebookDeveloperHolderLayout.setHorizontalGroup(
            notebookDeveloperHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 626, Short.MAX_VALUE)
        );
        notebookDeveloperHolderLayout.setVerticalGroup(
            notebookDeveloperHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 419, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(notebookDeveloperHolder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(notebookDeveloperHolder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel notebookDeveloperHolder;
    // End of variables declaration//GEN-END:variables
}
