/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package littlemangame;

import GameGui.BaseGameGui;
import littlemangame.genericGui.NotebookDeveloperGui;

/**
 *
 * @author brian
 */
public class LittleManGui extends BaseGameGui {

    /**
     * Creates new form LittleManGui
     */
    public LittleManGui() {
        super();
        initComponents();
    }

    public NotebookDeveloperGui getNotebookDeveloperGui() {
        return baseNotebookDeveloperGui1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        baseNotebookDeveloperGui1 = new littlemangame.notebookdeveloper.gui.BaseNotebookDeveloperGui();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(baseNotebookDeveloperGui1, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(baseNotebookDeveloperGui1, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private littlemangame.notebookdeveloper.gui.BaseNotebookDeveloperGui baseNotebookDeveloperGui1;
    // End of variables declaration//GEN-END:variables
}
