/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package littlemangame.computer;

import java.awt.Point;
import littlemangame.word.Word;

/**
 *
 * @author brian
 */
public class InputPanel extends javax.swing.JPanel {

    private boolean isValueSelected;
    private Word value;

    /**
     * Creates new form InputPanel
     */
    public InputPanel() {
        initComponents();
        wordSelector.setEditable(false);
        disablePanel();
    }

    public final void disablePanel() {
        wordSelector.setEnabled(false);
        submitButton.setEnabled(false);
        isValueSelected = false;
    }

    public void enablePanel() {
        wordSelector.setEnabled(true);
        submitButton.setEnabled(true);
    }

    public boolean isPanelEnabled() {
        return wordSelector.isEnabled();
    }

    public Word getLastSelectedWord() {
        disablePanel();
        return value;
    }

    public boolean isValueSelected() {
        return isValueSelected;
    }

    public Point getAccessLocation() {
        final int x = getX() + getWidth() + 4;
        final int y = getY() + getHeight() / 2;
        return new Point(x, y);
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        submitButton = new javax.swing.JButton();
        wordSelector = new littlemangame.notebookdeveloper.gui.WordSelector();

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(submitButton, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(wordSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(wordSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        value = wordSelector.getLastSelectedWord();
        isValueSelected = true;
    }//GEN-LAST:event_submitButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton submitButton;
    private littlemangame.notebookdeveloper.gui.WordSelector wordSelector;
    // End of variables declaration//GEN-END:variables

}
