/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package littlemangame.genericGui;

import java.awt.GridLayout;
import littlemangame.littlemancommands.LittleManCommander;
import littlemangame.notebookdeveloper.gui.OfficeView;
import littlemangame.notebookdeveloper.submissioncontrols.SubmissionControlGui;

/**
 *
 * @author brian
 */
public class NotebookDeveloperGui<T extends SubmissionControlGui> extends javax.swing.JPanel {

    protected final T submissionControllerGui;

    /**
     * Creates new form NotebookDeveloperGui
     *
     * @param submissionControllerGui
     */
    public NotebookDeveloperGui(T submissionControllerGui) {
        initComponents();
        this.submissionControllerGui = submissionControllerGui;
        submissionControllerGuiHolder.setLayout(new GridLayout());
        submissionControllerGuiHolder.add(submissionControllerGui);
    }

    public OfficeView getOfficeView() {
        return officeView;
    }

    public void registerLittleManCommander(LittleManCommander littleManCommander) {
        officeView.registerLittleManCommander(littleManCommander);
    }

    public T getSubmissionControlGui() {
        return submissionControllerGui;
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        officeView = new littlemangame.notebookdeveloper.gui.OfficeView();
        submissionControllerGuiHolder = new javax.swing.JPanel();

        javax.swing.GroupLayout submissionControllerGuiHolderLayout = new javax.swing.GroupLayout(submissionControllerGuiHolder);
        submissionControllerGuiHolder.setLayout(submissionControllerGuiHolderLayout);
        submissionControllerGuiHolderLayout.setHorizontalGroup(
            submissionControllerGuiHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 567, Short.MAX_VALUE)
        );
        submissionControllerGuiHolderLayout.setVerticalGroup(
            submissionControllerGuiHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(officeView, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 30, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(submissionControllerGuiHolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(officeView, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(submissionControllerGuiHolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private littlemangame.notebookdeveloper.gui.OfficeView officeView;
    private javax.swing.JPanel submissionControllerGuiHolder;
    // End of variables declaration//GEN-END:variables
}
